# Generated by Django 3.2.6 on 2021-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_mainsitemodels_youtube_silka'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenumodels',
            name='web_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homecaruselmodel',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
