# Generated by Django 3.2.6 on 2021-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_futuremodels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMaydon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maydon', models.SmallIntegerField()),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
            ],
        ),
    ]
