# Generated by Django 3.2.6 on 2021-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_newsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
