# Generated by Django 3.2.6 on 2021-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_newsmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.SmallIntegerField()),
                ('tarif', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=100)),
            ],
        ),
    ]
