# Generated by Django 3.2.6 on 2021-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_newsprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
