# Generated by Django 3.2.6 on 2021-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_rename_full_name_xodimmodel_ism'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasePage',
        ),
        migrations.AlterField(
            model_name='xodimmodel',
            name='birth_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='xodimmodel',
            name='ism',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='xodimmodel',
            name='lavozim',
            field=models.CharField(max_length=250),
        ),
    ]
