# Generated by Django 3.2.6 on 2021-08-16 22:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20210816_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='homecaruselmodel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainsitemodels',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
