# Generated by Django 3.2.6 on 2021-09-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_homecaruselmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsprise',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
