# Generated by Django 3.2.6 on 2021-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_newsprise_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsprise',
            name='price',
            field=models.IntegerField(),
        ),
    ]
