# Generated by Django 3.2.6 on 2021-08-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_submenumodels_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsitemodels',
            name='icon',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
