# Generated by Django 3.2.6 on 2021-08-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_mainsitemodels_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuremodels',
            name='main_text',
        ),
    ]
