# Generated by Django 3.2.6 on 2021-08-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_aboutmaydon_basepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmaydon',
            name='maydon',
            field=models.FloatField(),
        ),
    ]
