# Generated by Django 3.2.6 on 2021-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_xodimmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
