# Generated by Django 3.2.6 on 2021-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_mainsitemodels_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecaruselmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title karusel'),
        ),
    ]
